### ISSUE TITLE
The Max Tokens shows the same info that Max Output Tokens

### ISSUE THREAD

**Issue by softwareengineer-imerjr** [Ahmet-Dedeler/ai-llm-comparison#3]
In my opinion, merging fields that consistently display the same data would be beneficial. It'll tidy things up and improve usability.

**Comment by Ahmet-Dedeler** [comment]
Just realized that it is supposed to be input tokens and output tokens, but we have the same value on both.

Will fix it! Thanks for letting me know.

**Comment by Ahmet-Dedeler** [comment]
fixed :)
